FROM node:18.16.1-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./

RUN npm install

# Copy application
COPY . .

# Vite development server
EXPOSE 4200

# Start Vite
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "4200"]
